./cs_dissTest | tee cs_dissTest.log
./k_diss_ILTtest | tee k_diss_ILTtest.log
./k_dissTest | tee k_dissTest.log
./k_exchArrhTest | tee k_exchArrhTest.log
./omegaBCEtest | tee omegaBCEtest.log
./omegaTest | tee omegaTest.log
./test_FHO | tee test_FHO.log
./vss_and_neutral_e | tee vss_and_neutral_e.log
./vssTest | tee vssTest.log
